package com.muyategna.backend.support.enums;

public enum ReportReason {
    PROVIDER_NOT_SHOWED_UP,
    PAYMENT_ISSUE,
    POOR_QUALITY_SERVICE,
    MISBEHAVIOR_OR_RUDE_BEHAVIOR,
    SERVICE_NOT_AS_DESCRIBED,
    DAMAGE_TO_PROPERTY,
    DELAYED_SERVICE,
    UNAUTHORIZED_CHARGES,
    SPAM_OR_FRAUD,
    SAFETY_CONCERNS,
    CANCELLATION_ISSUE,
    OTHER
}
